### ISSUE TITLE
Raw data preview missing

### ISSUE THREAD

**Issue by KKulma** [MangoTheCat/blog_strictly#2]
It would be worth adding `head()` or `glimpse()` of raw data.

After loading raw data you say that it needs some cleaning, but the reader can't see it. The first time they see the data is after you've applied `str_to_title()`.

**Comment by dougmet** [comment]
Yes I see what you mean. Not sure I want to show the data twice, but perhaps I could show the raw data and then after the light cleaning just show a little bit of the modified column.
